name: app_select_fields_example
description: Demo app for app_select_fields.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  app_select_fields:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
